/*
 * Copyright 2007 Jesse Andrews and Manish Singh
 *  
 * This file may be used under the terms of of the
 * GNU General Public License Version 2 or later (the "GPL"),
 * http://www.gnu.org/licenses/gpl.html
 *  
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 */

#include "nsISupports.idl"

interface nsISimpleEnumerator;

[scriptable, uuid(4d224890-6081-4631-8e20-157bbd338597)]
interface oyITaboo : nsISupports {
  void open(in AUTF8String aURL, in AUTF8String aWhere);
  boolean save(in AUTF8String aDescription);

  boolean isSaved(in AUTF8String aURL);

  void delete(in AUTF8String aURL);
  void undelete(in AUTF8String aURL);
  void reallyDelete(in AUTF8String aURL);

  nsISimpleEnumerator get(in AUTF8String filter, in boolean deleted);
};

[scriptable, uuid(46a873a2-e3b2-4438-9265-65464033d830)]
interface oyITabooInfo : nsISupports {
  attribute AUTF8String title;
  attribute AUTF8String url;
  attribute AUTF8String favicon;
  attribute AUTF8String description;
  attribute AUTF8String imageURL;
  attribute AUTF8String thumbURL;
  attribute PRTime created;
  attribute PRTime updated;
};
