#include "nsISupports.idl"

interface nsISimpleEnumerator;

[scriptable, uuid(8d5388b0-7490-47b0-a7e2-e92beadbb0db)]
interface oyITablets : nsISupports {
  void save(in unsigned long aIndex, in AUTF8String aDescription);
  void delete(in AUTF8String aURL);
  void open(in AUTF8String aURL, in AUTF8String aWhere);

  nsISimpleEnumerator getTablets();
};

[scriptable, uuid(446637e1-e732-4f21-9b30-175d2773768a)]
interface oyITabletInfo : nsISupports {
  attribute AUTF8String title;
  attribute AUTF8String url;
  attribute AUTF8String description;
  attribute AUTF8String imageURL;
  attribute PRTime timestamp;
};
