/*
 * Copyright 2007 Jesse Andrews and Manish Singh
 *  
 * This file may be used under the terms of of the
 * GNU General Public License Version 2 or later (the "GPL"),
 * http://www.gnu.org/licenses/gpl.html
 *  
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 */

#include "nsISupports.idl"

interface nsISimpleEnumerator;

[scriptable, uuid(8d5388b0-7490-47b0-a7e2-e92beadbb0db)]
interface oyITaboo : nsISupports {
  void open(in AUTF8String aURL, in AUTF8String aWhere);
  boolean save(in AUTF8String aDescription);

  void delete(in AUTF8String aURL);
  void undelete(in AUTF8String aURL);
  void reallyDelete(in AUTF8String aURL);

  nsISimpleEnumerator get(in AUTF8String filter, in boolean deleted);
};

[scriptable, uuid(446637e1-e732-4f21-9b30-175d2773768a)]
interface oyITabooInfo : nsISupports {
  attribute AUTF8String title;
  attribute AUTF8String url;
  attribute AUTF8String description;
  attribute AUTF8String imageURL;
  attribute PRTime created;
  attribute PRTime updated;
};
